# Generated by Django 5.1.5 on 2025-05-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
